markdown: rdiscount
pygments: true
permalink: /:title

theme:
  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: swanson
    #bitbucket: philipj
    hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: _swanson
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Tomek Kobyliński
  email: tomek.kobylinski@gmail.com
  tagline: "moje"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

